### ISSUE TITLE
Found out this might be default in PopOS for Finnish (Dvorak)

### ISSUE THREAD

**Issue by h8672** [brndd/dvorakfi#2]
Only difference is 5, with germ... key instead of '‰' promille.

Really like this layout as I can write a bit already on my second day already.

Edit:
Had trouble to add it on laptop... and fixed it simply with, which I may have added at some point on my pc.
``` gsettings set org.gnome.desktop.input-sources show-all-sources true ```

**Comment by brndd** [comment]
Yeah, the layout is available in the ["extras" section of xkeyboard-config](https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/blob/master/rules/base.extras.xml), which makes it available on basically all Linux systems, with the caveat that some desktop environments, notably Gnome, hide exotic layouts by default.

Glad to hear you're enjoying it!
